#!/bin/sh

# Install vim plugin manager (vim-plug)
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# source the custom bashrc in the main bashrc
echo "source .bashrc_custom" >> ~/.bashrc

# install the trueline bash prompt generator
curl -fLo ~/.trueline \
 	https://raw.githubusercontent.com/petobens/trueline/master/trueline.sh

# get nord dircolors
curl -flo ~/.nord_dircolors \
    https://raw.githubusercontent.com/arcticicestudio/nord-dircolors/develop/src/dir_colors
